# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trending' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trending
  pod 'Alamofire'
  pod 'SkeletonView'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 7.0'

end
